import ExcelJS from 'exceljs'
import { ipcMain } from 'electron';
import { loadDays } from "./loadXlsx.js"
import { dialog } from 'electron/remote';

// SUMMARY SHEET SETUP
async function summarySetup(workbook) {
  let sheetcount = 0
  workbook.worksheets.forEach(sheet => { sheetcount++ })

  let summarySheet = workbook.addWorksheet(`AUTOGENERATED SUMMARY ${sheetcount}`, { views: [{ state: 'frozen', ySplit: 9 }] });
  summarySheet.getRow(9).values = ['Day', 'Bettor', 'Team', 'Result', 'Amount', 'win/loss', 'tong', 'total', 'comm', 'com%']
  summarySheet.getRow(8, 9).fill = {
    type: 'pattern',
    pattern: 'solid',
    fgColor: { argb: "FFFF00" }
  };
  summarySheet.getRow(8, 9).border = {
    top: {style:'thin'},
    left: {style:'thin'},
    bottom: {style:'thin'},
    right: {style:'thin'}
  };

  summarySheet.getCell("E8").value = { formula: "SUM(E10:E1000)" }
  summarySheet.getCell("E8").numFmt = '[$₱-3409]#,##0.00'

  summarySheet.getCell("F8").value = { formula: "SUM(F10:F1000)" }
  summarySheet.getCell("F8").numFmt = '[$₱-3409]#,##0.00'

  summarySheet.getCell("G8").value = { formula: "SUM(G10:G1000)" }
  summarySheet.getCell("G8").numFmt = '[$₱-3409]#,##0.00'

  summarySheet.getCell("H8").value = { formula: "SUM(H10:H1000)" }
  summarySheet.getCell("H8").numFmt = '[$₱-3409]#,##0.00'

  summarySheet.getCell("I8").value = { formula: "SUM(I10:I1000)" }
  summarySheet.getCell("I8").numFmt = '[$₱-3409]#,##0.00'

  summarySheet.getCell("J8").value = { formula: "SUM(H8:I8)" }
  summarySheet.getCell("J8").numFmt = '[$₱-3409]#,##0.00'
  return summarySheet
}

export async function compileData(data) {
  ipcMain.handle('compileData', async (event, data) => {

    data = JSON.parse(data)
    let sheet = await summarySetup(wb2)
    let days = loadDays().map(day => { return day.name.substring(0, 3) })
    let rowIndex = 10
    days.forEach(day => {
      //console.log(data)
      data.forEach(player => {
        player.bets.forEach(bet => {
          if (day == bet.day) {
            // Variables that need calculation / has value based on other cells
            let winLose = bet.result.includes('lose') ? (bet.amount * -1) : (bet.amount)
            let team = (bet.team + " " + bet.teamExtra).includes("undefined") ? bet.team : bet.team + " " + bet.teamExtra
            let tong = bet.result.includes('lose') ? 0 : (winLose * player.tong)
            let total = winLose - tong
            let comm = bet.amount * player.comm
            let result = total + comm

            // Initialize each row
            let rowData = [bet.day, player.name, team, bet.result, bet.amount, winLose, tong, total, comm, player.comm, result]
            sheet.getRow(rowIndex).values = rowData
            sheet.getRow(rowIndex).outlineLevel = 1;

            sheet.getRow(rowIndex).getCell(4).dataValidation = {
              type: 'list',
              allowBlank: false,
              formulae: ['"win,lose"']
            }
            sheet.getRow(rowIndex).getCell(5).numFmt = '[$₱-3409]#,##0.00'
            sheet.getRow(rowIndex).getCell(6).numFmt = '[$₱-3409]#,##0.00'
            sheet.getRow(rowIndex).getCell(7).numFmt = '[$₱-3409]#,##0.00'
            sheet.getRow(rowIndex).getCell(8).numFmt = '[$₱-3409]#,##0.00'
            sheet.getRow(rowIndex).getCell(9).numFmt = '[$₱-3409]#,##0.00'

            sheet.getRow(rowIndex).getCell(11).numFmt = '[$₱-3409]#,##0.00'


            // Change com% column values to percentage format
            sheet.getCell(rowIndex, 10).numFmt = '0.00%'

            // move to next row
            rowIndex++
          }
        })
      })
    })

    let now = new Date().toISOString().split('T')[0];
    let options = {
      title: "Save Excel File",
      defaultPath: now,
      buttonLabel: "Compile Data",

      filters: [
        { name: 'xlsx', extensions: ['xlsx'] }
      ]
    };
    dialog.showSaveDialog(null, options).then(async ({ filePath }) => {
      await wb2.xlsx.writeFile(filePath).catch(err => console.log(err))
    });


  })
}

const wb2 = new ExcelJS.Workbook()
